services:
  - type: web
    name: ae-payment-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PHONEPE_CLIENT_ID
        value: M22SXD53UEY41_2606112015
      - key: PHONEPE_CLIENT_SECRET
        value: NzRjNGM1YzYtMjEwYi00ZGRhLWFjOWQtNGZjMzU4NTQwNTc3
      - key: PHONEPE_SALT_KEY
        value: 099eb0cd-02cf-4e2a-8aca-3e6c6aff0399
      - key: PHONEPE_SANDBOX
        value: "true"
      - key: PORT
        value: "3001"
