services:
  - type: web
    name: ae-payment-server
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: PHONEPE_SANDBOX
        value: false
      - key: PHONEPE_CLIENT_ID
        sync: false
      - key: PHONEPE_CLIENT_SECRET
        sync: false
      - key: PHONEPE_WEBHOOK_USERNAME
        sync: false
      - key: PHONEPE_WEBHOOK_PASSWORD
        sync: false
      - key: CALLBACK_URL
        value: https://ae-payment-server.vercel.app/callback
      - key: SUCCESS_URL
        value: https://anshumanenterprises.online/payment-success.html
      - key: FAILURE_URL
        value: https://anshumanenterprises.online/payment-failure.html
